name: ðŸš€ Deploy via FTP

on:
  push:
    branches:
      - main # ou "master" se for o seu branch principal

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ§¾ Checkout do cÃ³digo
        uses: actions/checkout@v3

      - name: ðŸš€ Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST}}
          username: ${{ secrets.FTP_USERNAME}}
          password: ${{ secrets.FTP_PASSWORD}}
          protocol: ftps
          port: 21
          local-dir: ./
          server-dir: ./
          exclude: |
            **/.git/**
            **/.github/**
            **/.gitignore
            **/README.md
            **/.env
            **/uploads/**
          timeout: 600
          state-name: .ftp-deploy-sync-state.json
          