name: Deploy AlwaysData (SSH)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SCP (AlwaysData)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ssh1.alwaysdata.net
          port: 22
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}

          source: "."
          target: "/home/${{ secrets.SSH_USERNAME }}/www/"

          overwrite: true
          rm: false

          timeout: 120s
          command_timeout: 10m
