name: ðŸš€ Deploy via FTP

on:
  push:
    branches:
      - main # ou "master" se for o seu branch principal

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ§¾ Checkout do cÃ³digo
        uses: actions/checkout@v3

      - name: ðŸš€ Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_HOST}}
          username: ${{ secrets.FTP_USERNAME}}
          password: ${{ secrets.FTP_PASSWORD}}
          port: 22
          local-path: ./
          remote-path: /htdocs/
          exclude: |
            **/.git/**
            **/.github/**
            **/.gitignore
            **/README.md
            **/.env
            **/uploads/**
          